const fs=require('fs')
fs.writeFileSync('./numbers.txt', 1 )
fs.writeFileSync('./numbers.txt', 2 )
fs.writeFileSync('./numbers.txt', 3 )
fs.writeFileSync('./numbers.txt', 4 )
fs.writeFileSync('./numbers.txt', 1 )
fs.writeFileSync('./numbers.txt', 1 )
fs.writeFileSync('./numbers.txt', 1 )
console.log("done")